# Generated by Django 4.0.6 on 2022-07-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '附件', 'verbose_name_plural': '附件列表'},
        ),
        migrations.AlterModelOptions(
            name='userpicture',
            options={'verbose_name': '个人照片', 'verbose_name_plural': '个人照片列表'},
        ),
    ]
