# Generated by Django 4.0.6 on 2022-07-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_attachment_options_alter_userpicture_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPicture',
            new_name='Picture',
        ),
    ]
