# Generated by Django 4.0.6 on 2022-07-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_city_jobtype_alter_job_job_city_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市列表'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': '职位类型', 'verbose_name_plural': '职位类型'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='name',
            new_name='jobtype_name',
        ),
    ]
