# Generated by Django 4.0.6 on 2022-07-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_city_options_alter_jobtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='file/', verbose_name='简历附件'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='bachelor_school',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='本科学校'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='doctor_school',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='博士生学校'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='master_school',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='研究生学校'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='个人照片'),
        ),
    ]
