# Generated by Django 4.0.6 on 2022-07-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_userpicture_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': '个人照片', 'verbose_name_plural': '个人照片'},
        ),
    ]
