# Generated by Django 4.0.6 on 2022-07-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_resume_attachment_alter_resume_bachelor_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='apply_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.job', verbose_name='应聘职位'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.city', verbose_name='城市'),
        ),
    ]
