# Generated by Django 4.0.6 on 2022-07-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_resume_apply_position_alter_resume_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='has_goto_interview',
            field=models.BooleanField(default=False, verbose_name='已进入面试'),
        ),
    ]
