# Generated by Django 4.0.6 on 2022-07-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_resume_has_goto_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='born_address',
            new_name='from_address',
        ),
    ]
