# Generated by Django 4.0.6 on 2022-07-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_candidate_first_interviewer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='userid',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='apply_position',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='应聘职位'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bachelor_school',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='本科学校'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='born_address',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='生源地'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_remark',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='候选人信息备注'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=135, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='degree',
            field=models.CharField(blank=True, choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=135, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='doctor_school',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='博士生学校'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=135, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='major',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='master_school',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='研究生学校'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=135, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='username',
            field=models.CharField(max_length=135, null=True, verbose_name='姓名'),
        ),
    ]
