# Generated by Django 4.0.6 on 2022-07-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_candidate_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='born_address',
            new_name='from_address',
        ),
    ]
